import { createContext, useContext, useState, useEffect, useCallback, type ReactNode } from "react";
import { API_BASE } from "@/lib/api";

export type Language = "en" | "hi" | "kn";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LANG_KEY = "ecolog-language";
const CACHE_KEY = "ecolog-translations";
const CACHE_VERSION = 2; // bump when EN map changes

const translationsCache: Record<string, Record<string, string>> = {};

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: (key: string) => key,
});

export const useLanguage = () => useContext(LanguageContext);

const EN: Record<string, string> = {
  "lang.name": "English",
  "lang.hindi": "Hindi",
  "lang.kannada": "Kannada",
  "settings.language": "Language",
  "settings.notifications": "Notifications",
  "settings.darkMode": "Dark Mode",
  "settings.signOut": "Sign Out",
  "settings.editProfile": "Edit Profile",
  "stats.today": "Today CO₂",
  "stats.daysActive": "Days Active",
  "stats.rank": "Rank",
  "profile.dailyGoal": "Daily CO₂ budget",
  "profile.badges": "Badges",
  "profile.displayName": "Display Name",
  "profile.college": "College / Institution",
  "profile.age": "Age",
  "profile.gender": "Gender",
  "profile.bio": "Bio",
  "profile.phone": "Phone",
  "profile.yearOfStudy": "Year of Study",
  "profile.save": "Save Changes",
  "profile.city": "City",
  "profile.namePlaceholder": "Your name",
  "profile.cityPlaceholder": "e.g. Mangaluru",
  "profile.collegePlaceholder": "e.g. SIT Mangaluru",
  "profile.selectGender": "Select Gender",
  "profile.bioPlaceholder": "A short bio about you...",
  "profile.phonePlaceholder": "e.g. +91 9876543210",
  "profile.yearPlaceholder": "e.g. 2nd Year",
  "insights.title": "Your Insights",
  "insights.subtitle": "AI-powered analysis of your footprint.",
  "insights.30dayTrend": "30-Day Trend",
  "insights.categoryBreakdown": "Category Breakdown",
  "insights.carbonStory": "Your Carbon Story",
  "insights.bestDay": "Best day",
  "insights.streak": "Streak",
  "insights.savedVsCity": "Saved vs city",
  "insights.reductionPlan": "Your 30-Day Reduction Plan",
  "insights.planError": "Could not generate plan",
  "insights.generatingPlan": "Generating your plan…",
  "insights.firestoreLabel": "Your actual daily CO₂ from Firestore",
  "insights.breakdownEmpty": "Log activities to see your breakdown",
  "plan.week": "Week",
  "plan.savingPerMonth": "kg/month",
  "difficulty.easy": "Easy",
  "difficulty.medium": "Medium",
  "difficulty.hard": "Hard",
  "plan.action.1": "Switch to public transport for short commutes",
  "plan.tip.1": "Use metro or city buses instead of auto-rickshaws for daily office commutes",
  "plan.action.2": "Replace one meat meal per week with a plant-based option",
  "plan.tip.2": "Try masala dosa, chole bhature, or paneer butter masala as filling vegetarian options",
  "plan.action.3": "Unplug electronics when not in use",
  "plan.tip.3": "Switch off TV, laptop charger, and WiFi router at night — BESCOM bills drop noticeably",
  "plan.action.4": "Shop second-hand or upcycle instead of buying new",
  "plan.tip.4": "Check OLX, Cashify, or local Sunday flea markets for refurbished electronics and furniture",
  "plan.action.5": "Walk or cycle for trips under 2 km",
  "plan.tip.5": "Use a bicycle or simply walk for nearby errands like buying vegetables from the local sabzi mandi",
  "plan.action.6": "Reduce food waste by meal planning",
  "plan.tip.6": "Plan weekly meals around seasonal Indian vegetables — they're cheaper and have lower carbon impact",
  "plan.action.7": "Use energy-efficient appliances and LEDs",
  "plan.tip.7": "Replace old ceiling fans with BEE 5-star rated ones and use LED bulbs throughout the house",
  "plan.action.8": "Say no to single-use plastics",
  "plan.tip.8": "Carry a cloth bag for grocery shopping and refuse plastic straws at tea stalls and juice shops",
  "weeklySummary.title": "This Week's Summary",
  "weeklySummary.placeholder": "Your weekly carbon report is cooking. Keep logging activities to generate insights!",
  "weeklySummary.avgPerDay": "Avg/Day",
  "weeklySummary.bestDay": "Best Day",
  "weeklySummary.streak": "Streak",
  "weeklySummary.getPlan": "Get next week's plan",
  "dashboard.quickLog": "Quick Log",
  "dashboard.topEmission": "Top Emission",
  "dashboard.aiInsight": "AI Insight",
  "dashboard.poweredBy": "Powered by Gemini",
  "dashboard.tapToLog": "tap to log",
  "dashboard.goalUsed": "% of daily goal used",
  "dashboard.days": "days",
  "dashboard.ofGoal": "of {goal} goal",
  "dashboard.kgCO2": "kg CO₂",
  "log.title": "What did you do today?",
  "log.subtitle": "Tap an activity to log it.",
  "log.search": "Search activities…",
  "log.quantity": "Quantity ({unit})",
  "log.totalImpact": "Total impact:",
  "log.logIt": "Log it",
  "log.perUnit": "g CO₂ per {unit}",
  "log.calculatedImpact": "Calculated CO₂ Impact",
  "log.activityType": "Activity Type",
  "log.submit": "Log Activity",
  "log.header": "Log {category} Activity",
  "unit.km": "km",
  "unit.meal": "meal",
  "unit.kWh": "kWh",
  "unit.hour": "hour",
  "unit.cycle": "cycle",
  "unit.order": "order",
  "unit.item": "item",
  "unit.bag": "bag",
  "unit.kg": "kg",
  "unit.g": "g",
  "leaderboard.title": "Leaderboard",
  "leaderboard.subtitle": "Compete with eco-warriors.",
  "leaderboard.yourRank": "Your Rank",
  "leaderboard.topWarriors": "Top Warriors",
  "leaderboard.empty": "No eco-warriors found in this view.",
  "leaderboard.today": "Today",
  "leaderboard.weekly": "Weekly",
  "leaderboard.monthly": "Monthly",
  "leaderboard.global": "Global",
  "leaderboard.city": "City",
  "detailedInsight.title": "EcoLog AI",
  "detailedInsight.errorTitle": "Oops! Something went wrong.",
  "detailedInsight.goBack": "Go Back",
  "detailedInsight.askEcoLogAI": "Ask EcoLog AI",
  "detailedInsight.chatPlaceholder": "How can I help you today?",
  "detailedInsight.chatSubtext": "Ask me anything about your carbon footprint, tips to reduce emissions, or your trends.",
  "detailedInsight.q1": "How can I reduce my footprint?",
  "detailedInsight.q2": "What's my biggest emission?",
  "detailedInsight.q3": "Tips for this week?",
  "detailedInsight.inputPlaceholder": "Ask a question about this report...",
  "leaderboard.kgCO2": "kg CO₂",
  "leaderboard.period.today": "Today",
  "leaderboard.period.weekly": "Weekly",
  "leaderboard.period.monthly": "Monthly",
  "leaderboard.scope.global": "Global",
  "leaderboard.scope.city": "City",
  "badge.firstLog": "First Log",
  "badge.sevenDay": "7-Day Streak",
  "badge.carbonHero": "Carbon Hero",
  "badge.greenCommuter": "Green Commuter",
  "badge.cityTop10": "City Top 10",
  "badge.ecoWarrior": "Eco Warrior",
  "navbar.appName": "EcoLog",
  "navbar.days": "days",
  "nav.home": "Home",
  "nav.insights": "Insights",
  "nav.log": "Log",
  "nav.top": "Top",
  "nav.me": "Me",
  "nav.quickLog": "Quick log",
  "onboarding.welcome": "Welcome to",
  "onboarding.tagline": "Track your carbon. Change your world.",
  "onboarding.step1.title": "Track",
  "onboarding.step1.body": "Log your daily transport, food, energy & shopping in seconds.",
  "onboarding.step2.title": "AI Tip",
  "onboarding.step2.body": "Personalised tips tailored to your life — not generic advice.",
  "onboarding.step3.title": "Complete",
  "onboarding.step3.body": "Beat your goals with streaks and badges.",
  "onboarding.step4.title": "Run",
  "onboarding.step4.body": "Join the city leaderboard and make sustainability a habit.",
  "onboarding.step5.title": "Get Started",
  "onboarding.step5.body": "Sign in to begin your journey to a greener future.",
  "onboarding.signIn": "Sign in with Google",
  "category.transport": "Transport",
  "category.food": "Food",
  "category.energy": "Energy",
  "category.shopping": "Shopping",
  "activity.car_petrol": "Car (Petrol)",
  "activity.car_diesel": "Car (Diesel)",
  "activity.bike_activa": "Activa/Bike",
  "activity.e_scooter": "E-Scooter",
  "activity.auto_rickshaw": "Auto Rickshaw",
  "activity.bus": "Bus",
  "activity.train": "Train",
  "activity.flight_domestic": "Flight",
  "activity.bike_ride": "Bike Ride",
  "activity.walk": "Walk",
  "activity.veg_meal": "Veg Meal",
  "activity.nonveg_meal": "Non-veg Meal",
  "activity.dairy_meal": "Dairy Meal",
  "activity.egg_meal": "Egg Meal",
  "activity.street_food": "Street Food",
  "activity.swiggy_zomato": "Swiggy/Zomato",
  "activity.electricity_kwh": "Electricity",
  "activity.lpg_cylinder": "LPG Cylinder",
  "activity.ac_hour": "AC Usage",
  "activity.geyser_hour": "Geyser",
  "activity.washing_machine": "Washing Machine",
  "activity.online_order": "Online Order",
  "activity.clothing_item": "Clothing Item",
  "activity.electronics": "Electronics",
  "activity.plastic_bag": "Plastic Bag",
  "activity.zeroImpact": "0g · zero impact",
  "tab.all": "All",
  "gender.male": "Male",
  "gender.female": "Female",
  "gender.other": "Other",
  "gender.preferNot": "Prefer not to say",
};

const HI: Record<string, string> = {
  "lang.name": "अंग्रेज़ी",
  "lang.hindi": "हिंदी",
  "lang.kannada": "कन्नड़",
  "settings.language": "भाषा",
  "settings.notifications": "सूचनाएं",
  "settings.darkMode": "डार्क मोड",
  "settings.signOut": "साइन आउट",
  "settings.editProfile": "प्रोफ़ाइल संपादित करें",
  "stats.today": "आज का CO₂",
  "stats.daysActive": "सक्रिय दिन",
  "stats.rank": "रैंक",
  "profile.dailyGoal": "दैनिक CO₂ बजट",
  "profile.badges": "बैज",
  "profile.displayName": "प्रदर्शन नाम",
  "profile.college": "कॉलेज / संस्थान",
  "profile.age": "आयु",
  "profile.gender": "लिंग",
  "profile.bio": "जीवनी",
  "profile.phone": "फ़ोन",
  "profile.yearOfStudy": "अध्ययन वर्ष",
  "profile.save": "बदलाव सहेजें",
  "profile.city": "शहर",
  "profile.namePlaceholder": "आपका नाम",
  "profile.cityPlaceholder": "जैसे मंगलुरु",
  "profile.collegePlaceholder": "जैसे SIT मंगलुरु",
  "profile.selectGender": "लिंग चुनें",
  "profile.bioPlaceholder": "आपके बारे में संक्षिप्त जानकारी...",
  "profile.phonePlaceholder": "जैसे +91 9876543210",
  "profile.yearPlaceholder": "जैसे द्वितीय वर्ष",
  "insights.title": "आपकी अंतर्दृष्टि",
  "insights.subtitle": "AI-संचालित आपके कार्बन पदचिह्न का विश्लेषण।",
  "insights.30dayTrend": "30-दिन का रुझान",
  "insights.categoryBreakdown": "श्रेणी विभाजन",
  "insights.carbonStory": "आपकी कार्बन कहानी",
  "insights.bestDay": "सर्वश्रेष्ठ दिन",
  "insights.streak": "लगातार",
  "insights.savedVsCity": "शहर की तुलना में बचत",
  "insights.reductionPlan": "आपकी 30-दिन की कमी योजना",
  "insights.planError": "योजना उत्पन्न नहीं की जा सकी",
  "insights.generatingPlan": "आपकी योजना तैयार हो रही है…",
  "insights.firestoreLabel": "Firestore से आपका वास्तविक दैनिक CO₂",
  "insights.breakdownEmpty": "अपना विभाजन देखने के लिए गतिविधियाँ लॉग करें",
  "plan.week": "सप्ताह",
  "plan.savingPerMonth": "किग्रा/माह",
  "difficulty.easy": "आसान",
  "difficulty.medium": "मध्यम",
  "difficulty.hard": "कठिन",
  "plan.action.1": "छोटी दूरी के लिए सार्वजनिक परिवहन का उपयोग करें",
  "plan.tip.1": "दैनिक कार्यालय आवागमन के लिए ऑटो-रिक्शा के बजाय मेट्रो या सिटी बसों का उपयोग करें",
  "plan.action.2": "प्रति सप्ताह एक मांस भोजन को पौध-आधारित विकल्प से बदलें",
  "plan.tip.2": "भरपूर शाकाहारी विकल्प के रूप में मसाला डोसा, छोले भटूरे, या पनीर बटर मसाला आज़माएं",
  "plan.action.3": "उपयोग में न होने पर इलेक्ट्रॉनिक्स को अनप्लग करें",
  "plan.tip.3": "रात में टीवी, लैपटॉप चार्जर और वाईफाई राउटर बंद कर दें",
  "plan.action.4": "नया खरीदने के बजाय सेकंड-हैंड खरीदें या अपसाइकिल करें",
  "plan.tip.4": "नवीनीकृत इलेक्ट्रॉनिक्स और फर्नीचर के लिए OLX, Cashify, या स्थानीय बाजार देखें",
  "plan.action.5": "2 किमी से कम की यात्रा के लिए पैदल चलें या साइकिल चलाएं",
  "plan.tip.5": "स्थानीय सब्जी मंडी से सब्जियां खरीदने जैसे निकट के कामों के लिए साइकिल या पैदल चलें",
  "plan.action.6": "भोजन योजना द्वारा भोजन की बर्बादी कम करें",
  "plan.tip.6": "मौसमी भारतीय सब्जियों के आसपास साप्ताहिक भोजन की योजना बनाएं",
  "plan.action.7": "ऊर्जा-कुशल उपकरणों और LED का उपयोग करें",
  "plan.tip.7": "पुराने पंखों को BEE 5-स्टार रेटेड से बदलें और पूरे घर में LED बल्ब का उपयोग करें",
  "plan.action.8": "एकल-उपयोग प्लास्टिक को ना कहें",
  "plan.tip.8": "किराने की खरीदारी के लिए कपड़े का थैला ले जाएं और प्लास्टिक के स्ट्रॉ को मना करें",
  "weeklySummary.title": "इस सप्ताह का सारांश",
  "weeklySummary.placeholder": "आपकी साप्ताहिक कार्बन रिपोर्ट तैयार हो रही है। अंतर्दृष्टि के लिए गतिविधियाँ लॉग करते रहें!",
  "weeklySummary.avgPerDay": "औसत/दिन",
  "weeklySummary.bestDay": "सर्वश्रेष्ठ दिन",
  "weeklySummary.streak": "लगातार",
  "weeklySummary.getPlan": "अगले सप्ताह की योजना प्राप्त करें",
  "dashboard.quickLog": "त्वरित लॉग",
  "dashboard.topEmission": "शीर्ष उत्सर्जन",
  "dashboard.aiInsight": "AI अंतर्दृष्टि",
  "dashboard.poweredBy": "Gemini द्वारा संचालित",
  "dashboard.tapToLog": "लॉग करने के लिए टैप करें",
  "dashboard.goalUsed": "दैनिक लक्ष्य का उपयोग %",
  "dashboard.days": "दिन",
  "dashboard.ofGoal": "{goal} लक्ष्य में से",
  "dashboard.kgCO2": "किग्रा CO₂",
  "log.title": "आज आपने क्या किया?",
  "log.subtitle": "लॉग करने के लिए गतिविधि पर टैप करें।",
  "log.search": "गतिविधियाँ खोजें…",
  "log.quantity": "मात्रा ({unit})",
  "log.totalImpact": "कुल प्रभाव:",
  "log.logIt": "लॉग करें",
  "log.perUnit": "ग्राम CO₂ प्रति {unit}",
  "log.calculatedImpact": "गणना किया गया CO₂ प्रभाव",
  "log.activityType": "गतिविधि प्रकार",
  "log.submit": "गतिविधि लॉग करें",
  "log.header": "{category} गतिविधि लॉग करें",
  "unit.km": "किमी",
  "unit.meal": "भोजन",
  "unit.kWh": "किलोवाट घंटा",
  "unit.hour": "घंटा",
  "unit.cycle": "चक्र",
  "unit.order": "ऑर्डर",
  "unit.item": "वस्तु",
  "unit.bag": "थैला",
  "unit.kg": "किग्रा",
  "unit.g": "ग्राम",
  "leaderboard.title": "लीडरबोर्ड",
  "leaderboard.subtitle": "इको-योद्धाओं से प्रतिस्पर्धा करें।",
  "leaderboard.yourRank": "आपकी रैंक",
  "leaderboard.topWarriors": "शीर्ष योद्धा",
  "leaderboard.empty": "इस दृश्य में कोई इको-योद्धा नहीं मिला।",
  "leaderboard.today": "आज",
  "leaderboard.weekly": "साप्ताहिक",
  "leaderboard.monthly": "मासिक",
  "leaderboard.global": "वैश्विक",
  "leaderboard.city": "शहर",
  "detailedInsight.title": "EcoLog AI",
  "detailedInsight.errorTitle": "ओह! कुछ गलत हो गया।",
  "detailedInsight.goBack": "वापस जाएं",
  "detailedInsight.askEcoLogAI": "EcoLog AI से पूछें",
  "detailedInsight.chatPlaceholder": "आज मैं आपकी कैसे मदद कर सकता हूं?",
  "detailedInsight.chatSubtext": "अपने कार्बन पदचिह्न, उत्सर्जन कम करने के टिप्स, या अपने रुझानों के बारे में मुझसे कुछ भी पूछें।",
  "detailedInsight.q1": "मैं अपना कार्बन पदचिह्न कैसे कम कर सकता हूं?",
  "detailedInsight.q2": "मेरा सबसे बड़ा उत्सर्जन क्या है?",
  "detailedInsight.q3": "इस सप्ताह के लिए टिप्स?",
  "detailedInsight.inputPlaceholder": "इस रिपोर्ट के बारे में प्रश्न पूछें...",
  "leaderboard.kgCO2": "किग्रा CO₂",
  "leaderboard.period.today": "आज",
  "leaderboard.period.weekly": "साप्ताहिक",
  "leaderboard.period.monthly": "मासिक",
  "leaderboard.scope.global": "वैश्विक",
  "leaderboard.scope.city": "शहर",
  "badge.firstLog": "पहला लॉग",
  "badge.sevenDay": "7-दिन का सिलसिला",
  "badge.carbonHero": "कार्बन हीरो",
  "badge.greenCommuter": "हरित यात्री",
  "badge.cityTop10": "शहर के शीर्ष 10",
  "badge.ecoWarrior": "इको योद्धा",
  "navbar.appName": "EcoLog",
  "navbar.days": "दिन",
  "nav.home": "होम",
  "nav.insights": "इनसाइट्स",
  "nav.log": "लॉग",
  "nav.top": "टॉप",
  "nav.me": "मैं",
  "nav.quickLog": "त्वरित लॉग",
  "onboarding.welcome": "स्वागत है",
  "onboarding.tagline": "अपना कार्बन ट्रैक करें। अपनी दुनिया बदलें।",
  "onboarding.step1.title": "ट्रैक करें",
  "onboarding.step1.body": "अपने दैनिक परिवहन, भोजन, ऊर्जा और खरीदारी को सेकंडों में लॉग करें।",
  "onboarding.step2.title": "AI सुझाव",
  "onboarding.step2.body": "आपके जीवन के अनुरूप व्यक्तिगत सुझाव — सामान्य सलाह नहीं।",
  "onboarding.step3.title": "पूरा करें",
  "onboarding.step3.body": "लगातार और बैज के साथ अपने लक्ष्यों को पार करें।",
  "onboarding.step4.title": "दौड़ें",
  "onboarding.step4.body": "शहर लीडरबोर्ड से जुड़ें और स्थिरता को एक आदत बनाएं।",
  "onboarding.step5.title": "शुरू करें",
  "onboarding.step5.body": "हरित भविष्य की अपनी यात्रा शुरू करने के लिए साइन इन करें।",
  "onboarding.signIn": "Google से साइन इन करें",
  "category.transport": "परिवहन",
  "category.food": "भोजन",
  "category.energy": "ऊर्जा",
  "category.shopping": "खरीदारी",
  "activity.car_petrol": "कार (पेट्रोल)",
  "activity.car_diesel": "कार (डीज़ल)",
  "activity.bike_activa": "एक्टिवा/बाइक",
  "activity.e_scooter": "ई-स्कूटर",
  "activity.auto_rickshaw": "ऑटो रिक्शा",
  "activity.bus": "बस",
  "activity.train": "ट्रेन",
  "activity.flight_domestic": "उड़ान",
  "activity.bike_ride": "साइकिल सवारी",
  "activity.walk": "पैदल चलना",
  "activity.veg_meal": "शाकाहारी भोजन",
  "activity.nonveg_meal": "मांसाहारी भोजन",
  "activity.dairy_meal": "डेयरी भोजन",
  "activity.egg_meal": "अंडा भोजन",
  "activity.street_food": "स्ट्रीट फूड",
  "activity.swiggy_zomato": "स्विगी/ज़ोमैटो",
  "activity.electricity_kwh": "बिजली",
  "activity.lpg_cylinder": "LPG सिलेंडर",
  "activity.ac_hour": "AC उपयोग",
  "activity.geyser_hour": "गीज़र",
  "activity.washing_machine": "वॉशिंग मशीन",
  "activity.online_order": "ऑनलाइन ऑर्डर",
  "activity.clothing_item": "कपड़े की वस्तु",
  "activity.electronics": "इलेक्ट्रॉनिक्स",
  "activity.plastic_bag": "प्लास्टिक बैग",
  "activity.zeroImpact": "0 ग्राम · शून्य प्रभाव",
  "tab.all": "सभी",
  "gender.male": "पुरुष",
  "gender.female": "महिला",
  "gender.other": "अन्य",
  "gender.preferNot": "कहना पसंद नहीं",
};

const KN: Record<string, string> = {
  "lang.name": "ಇಂಗ್ಲಿಷ್",
  "lang.hindi": "ಹಿಂದಿ",
  "lang.kannada": "ಕನ್ನಡ",
  "settings.language": "ಭಾಷೆ",
  "settings.notifications": "ಅಧಿಸೂಚನೆಗಳು",
  "settings.darkMode": "ಡಾರ್ಕ್ ಮೋಡ್",
  "settings.signOut": "ಸೈನ್ ಔಟ್",
  "settings.editProfile": "ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ",
  "stats.today": "ಇಂದಿನ CO₂",
  "stats.daysActive": "ಸಕ್ರಿಯ ದಿನಗಳು",
  "stats.rank": "ಶ್ರೇಣಿ",
  "profile.dailyGoal": "ದೈನಂದಿನ CO₂ ಬಜೆಟ್",
  "profile.badges": "ಬ್ಯಾಡ್ಜ್ಗಳು",
  "profile.displayName": "ಪ್ರದರ್ಶನ ಹೆಸರು",
  "profile.college": "ಕಾಲೇಜು / ಸಂಸ್ಥೆ",
  "profile.age": "ವಯಸ್ಸು",
  "profile.gender": "ಲಿಂಗ",
  "profile.bio": "ಜೀವನಚರಿತ್ರೆ",
  "profile.phone": "ಫೋನ್",
  "profile.yearOfStudy": "ಅಧ್ಯಯನ ವರ್ಷ",
  "profile.save": "ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ",
  "profile.city": "ನಗರ",
  "profile.namePlaceholder": "ನಿಮ್ಮ ಹೆಸರು",
  "profile.cityPlaceholder": "ಉದಾ. ಮಂಗಳೂರು",
  "profile.collegePlaceholder": "ಉದಾ. SIT ಮಂಗಳೂರು",
  "profile.selectGender": "ಲಿಂಗ ಆಯ್ಕೆಮಾಡಿ",
  "profile.bioPlaceholder": "ನಿಮ್ಮ ಬಗ್ಗೆ ಸಂಕ್ಷಿಪ್ತ ಮಾಹಿತಿ...",
  "profile.phonePlaceholder": "ಉದಾ. +91 9876543210",
  "profile.yearPlaceholder": "ಉದಾ. 2ನೇ ವರ್ಷ",
  "insights.title": "ನಿಮ್ಮ ಒಳನೋಟಗಳು",
  "insights.subtitle": "AI-ಚಾಲಿತ ನಿಮ್ಮ ಇಂಗಾಲದ ಹೆಜ್ಜೆಗುರುತಿನ ವಿಶ್ಲೇಷಣೆ.",
  "insights.30dayTrend": "30-ದಿನಗಳ ಪ್ರವೃತ್ತಿ",
  "insights.categoryBreakdown": "ವರ್ಗ ವಿಭಜನೆ",
  "insights.carbonStory": "ನಿಮ್ಮ ಇಂಗಾಲದ ಕಥೆ",
  "insights.bestDay": "ಅತ್ಯುತ್ತಮ ದಿನ",
  "insights.streak": "ಸ್ಟ್ರೀಕ್",
  "insights.savedVsCity": "ನಗರಕ್ಕೆ ಹೋಲಿಸಿದರೆ ಉಳಿತಾಯ",
  "insights.reductionPlan": "ನಿಮ್ಮ 30-ದಿನಗಳ ಕಡಿತ ಯೋಜನೆ",
  "insights.planError": "ಯೋಜನೆಯನ್ನು ರಚಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ",
  "insights.generatingPlan": "ನಿಮ್ಮ ಯೋಜನೆಯನ್ನು ಸಿದ್ಧಪಡಿಸಲಾಗುತ್ತಿದೆ…",
  "insights.firestoreLabel": "Firestore ನಿಂದ ನಿಮ್ಮ ನಿಜವಾದ ದೈನಂದಿನ CO₂",
  "insights.breakdownEmpty": "ನಿಮ್ಮ ವಿಭಜನೆಯನ್ನು ನೋಡಲು ಚಟುವಟಿಕೆಗಳನ್ನು ಲಾಗ್ ಮಾಡಿ",
  "plan.week": "ವಾರ",
  "plan.savingPerMonth": "ಕೆಜಿ/ತಿಂಗಳು",
  "difficulty.easy": "ಸುಲಭ",
  "difficulty.medium": "ಮಧ್ಯಮ",
  "difficulty.hard": "ಕಠಿಣ",
  "plan.action.1": "ಸಣ್ಣ ಪ್ರಯಾಣಕ್ಕೆ ಸಾರ್ವಜನಿಕ ಸಾರಿಗೆ ಬಳಸಿ",
  "plan.tip.1": "ದೈನಂದಿನ ಕಚೇರಿ ಪ್ರಯಾಣಕ್ಕೆ ಆಟೋ-ರಿಕ್ಷಾ ಬದಲು ಮೆಟ್ರೋ ಅಥವಾ ಸಿಟಿ ಬಸ್ ಬಳಸಿ",
  "plan.action.2": "ವಾರಕ್ಕೆ ಒಂದು ಮಾಂಸಾಹಾರವನ್ನು ಸಸ್ಯಾಹಾರಿ ಆಯ್ಕೆಯಿಂದ ಬದಲಿಸಿ",
  "plan.tip.2": "ತುಂಬುವ ಸಸ್ಯಾಹಾರಿ ಆಯ್ಕೆಗಳಾಗಿ ಮಸಾಲೆ ದೋಸೆ, ಛೋಲೆ ಭಟೂರೆ, ಅಥವಾ ಪನೀರ್ ಬಟರ್ ಮಸಾಲಾ ಪ್ರಯತ್ನಿಸಿ",
  "plan.action.3": "ಬಳಕೆಯಲ್ಲಿಲ್ಲದಾಗ ಎಲೆಕ್ಟ್ರಾನಿಕ್ಸ್ ಅನ್ಪ್ಲಗ್ ಮಾಡಿ",
  "plan.tip.3": "ರಾತ್ರಿಯಲ್ಲಿ ಟಿವಿ, ಲ್ಯಾಪ್ಟಾಪ್ ಚಾರ್ಜರ್ ಮತ್ತು ವೈಫೈ ರೌಟರ್ ಆಫ್ ಮಾಡಿ",
  "plan.action.4": "ಹೊಸದನ್ನು ಖರೀದಿಸುವ ಬದಲು ಸೆಕೆಂಡ್-ಹ್ಯಾಂಡ್ ಖರೀದಿಸಿ ಅಥವಾ ಅಪ್ಸೈಕಲ್ ಮಾಡಿ",
  "plan.tip.4": "ನವೀಕರಿಸಿದ ಎಲೆಕ್ಟ್ರಾನಿಕ್ಸ್ ಮತ್ತು ಪೀಠೋಪಕರಣಗಳಿಗಾಗಿ OLX, Cashify, ಅಥವಾ ಸ್ಥಳೀಯ ಮಾರುಕಟ್ಟೆ ನೋಡಿ",
  "plan.action.5": "2 ಕಿಮೀ ಗಿಂತ ಕಡಿಮೆ ಪ್ರಯಾಣಕ್ಕೆ ನಡೆಯಿರಿ ಅಥವಾ ಸೈಕಲ್ ತೆಗೆದುಕೊಳ್ಳಿ",
  "plan.tip.5": "ಸ್ಥಳೀಯ ತರಕಾರಿ ಮಾರುಕಟ್ಟೆಗೆ ಹೋಗುವಂತಹ ಹತ್ತಿರದ ಕೆಲಸಗಳಿಗೆ ಸೈಕಲ್ ಅಥವಾ ನಡಿಗೆ ಬಳಸಿ",
  "plan.action.6": "ಊಟದ ಯೋಜನೆಯಿಂದ ಆಹಾರ ವ್ಯರ್ಥ ಕಡಿಮೆ ಮಾಡಿ",
  "plan.tip.6": "ಋತುಮಾನದ ಭಾರತೀಯ ತರಕಾರಿಗಳ ಸುತ್ತ ವಾರದ ಊಟ ಯೋಜಿಸಿ",
  "plan.action.7": "ಶಕ್ತಿ-ದಕ್ಷ ಉಪಕರಣಗಳು ಮತ್ತು LED ಗಳನ್ನು ಬಳಸಿ",
  "plan.tip.7": "ಹಳೆಯ ಸೀಲಿಂಗ್ ಫ್ಯಾನ್ಗಳನ್ನು BEE 5-ಸ್ಟಾರ್ ರೇಟೆಡ್ ನಿಂದ ಬದಲಿಸಿ ಮತ್ತು ಮನೆಯಾದ್ಯಂತ LED ಬಲ್ಬ್ ಬಳಸಿ",
  "plan.action.8": "ಏಕ-ಬಳಕೆಯ ಪ್ಲಾಸ್ಟಿಕ್ಗೆ ನಾ ಹೇಳಿ",
  "plan.tip.8": "ಕಿರಾಣಿ ಶಾಪಿಂಗ್ಗೆ ಬಟ್ಟೆಯ ಚೀಲ ತೆಗೆದುಕೊಂಡು ಹೋಗಿ ಮತ್ತು ಪ್ಲಾಸ್ಟಿಕ್ ಸ್ಟ್ರಾವನ್ನು ನಿರಾಕರಿಸಿ",
  "weeklySummary.title": "ಈ ವಾರದ ಸಾರಾಂಶ",
  "weeklySummary.placeholder": "ನಿಮ್ಮ ಸಾಪ್ತಾಹಿಕ ಇಂಗಾಲ ವರದಿ ಸಿದ್ಧವಾಗುತ್ತಿದೆ. ಒಳನೋಟಗಳಿಗಾಗಿ ಚಟುವಟಿಕೆಗಳನ್ನು ಲಾಗ್ ಮಾಡುತ್ತಿರಿ!",
  "weeklySummary.avgPerDay": "ಸರಾಸರಿ/ದಿನ",
  "weeklySummary.bestDay": "ಅತ್ಯುತ್ತಮ ದಿನ",
  "weeklySummary.streak": "ಸ್ಟ್ರೀಕ್",
  "weeklySummary.getPlan": "ಮುಂದಿನ ವಾರದ ಯೋಜನೆ ಪಡೆಯಿರಿ",
  "dashboard.quickLog": "ತ್ವರಿತ ಲಾಗ್",
  "dashboard.topEmission": "ಶ್ರೇಷ್ಠ ಹೊರಸೂಸುವಿಕೆ",
  "dashboard.aiInsight": "AI ಒಳನೋಟ",
  "dashboard.poweredBy": "Gemini ನಿಂದ ಚಾಲಿತ",
  "dashboard.tapToLog": "ಲಾಗ್ ಮಾಡಲು ಟ್ಯಾಪ್ ಮಾಡಿ",
  "dashboard.goalUsed": "ದೈನಂದಿನ ಗುರಿಯ % ಬಳಕೆ",
  "dashboard.days": "ದಿನಗಳು",
  "dashboard.ofGoal": "{goal} ಗುರಿಯಲ್ಲಿ",
  "dashboard.kgCO2": "ಕೆಜಿ CO₂",
  "log.title": "ಇಂದು ನೀವು ಏನು ಮಾಡಿದಿರಿ?",
  "log.subtitle": "ಲಾಗ್ ಮಾಡಲು ಚಟುವಟಿಕೆಯನ್ನು ಟ್ಯಾಪ್ ಮಾಡಿ.",
  "log.search": "ಚಟುವಟಿಕೆಗಳನ್ನು ಹುಡುಕಿ…",
  "log.quantity": "ಪ್ರಮಾಣ ({unit})",
  "log.totalImpact": "ಒಟ್ಟು ಪರಿಣಾಮ:",
  "log.logIt": "ಲಾಗ್ ಮಾಡಿ",
  "log.perUnit": "ಗ್ರಾಂ CO₂ ಪ್ರತಿ {unit}",
  "log.calculatedImpact": "ಲೆಕ್ಕಾಚಾರದ CO₂ ಪರಿಣಾಮ",
  "log.activityType": "ಚಟುವಟಿಕೆ ಪ್ರಕಾರ",
  "log.submit": "ಚಟುವಟಿಕೆ ಲಾಗ್ ಮಾಡಿ",
  "log.header": "{category} ಚಟುವಟಿಕೆ ಲಾಗ್ ಮಾಡಿ",
  "unit.km": "ಕಿಮೀ",
  "unit.meal": "ಊಟ",
  "unit.kWh": "ಕಿಲೋವ್ಯಾಟ್ ಗಂಟೆ",
  "unit.hour": "ಗಂಟೆ",
  "unit.cycle": "ಸೈಕಲ್",
  "unit.order": "ಆರ್ಡರ್",
  "unit.item": "ವಸ್ತು",
  "unit.bag": "ಚೀಲ",
  "unit.kg": "ಕೆಜಿ",
  "unit.g": "ಗ್ರಾಂ",
  "leaderboard.title": "ಲೀಡರ್ಬೋರ್ಡ್",
  "leaderboard.subtitle": "ಪರಿಸರ-ಯೋಧರೊಂದಿಗೆ ಸ್ಪರ್ಧಿಸಿ.",
  "leaderboard.yourRank": "ನಿಮ್ಮ ಶ್ರೇಣಿ",
  "leaderboard.topWarriors": "ಶ್ರೇಷ್ಠ ಯೋಧರು",
  "leaderboard.empty": "ಈ ವೀಕ್ಷಣೆಯಲ್ಲಿ ಯಾವುದೇ ಪರಿಸರ-ಯೋಧರು ಕಂಡುಬಂದಿಲ್ಲ.",
  "leaderboard.today": "ಇಂದು",
  "leaderboard.weekly": "ಸಾಪ್ತಾಹಿಕ",
  "leaderboard.monthly": "ಮಾಸಿಕ",
  "leaderboard.global": "ಜಾಗತಿಕ",
  "leaderboard.city": "ನಗರ",
  "detailedInsight.title": "EcoLog AI",
  "detailedInsight.errorTitle": "ಓಹ್! ಏನೋ ತಪ್ಪಾಗಿದೆ.",
  "detailedInsight.goBack": "ಹಿಂದಿರುಗಿ",
  "detailedInsight.askEcoLogAI": "EcoLog AI ಕೇಳಿ",
  "detailedInsight.chatPlaceholder": "ಇಂದು ನಾನು ನಿಮಗೆ ಹೇಗೆ ಸಹಾಯ ಮಾಡಬಹುದು?",
  "detailedInsight.chatSubtext": "ನಿಮ್ಮ ಇಂಗಾಲದ ಹೆಜ್ಜೆಗುರುತು, ಹೊರಸೂಸುವಿಕೆ ಕಡಿಮೆ ಮಾಡುವ ಸಲಹೆಗಳು, ಅಥವಾ ನಿಮ್ಮ ಪ್ರವೃತ್ತಿಗಳ ಬಗ್ಗೆ ನನ್ನನ್ನು ಏನು ಬೇಕಾದರೂ ಕೇಳಿ.",
  "detailedInsight.q1": "ನನ್ನ ಇಂಗಾಲದ ಹೆಜ್ಜೆಗುರುತನ್ನು ಹೇಗೆ ಕಡಿಮೆ ಮಾಡುವುದು?",
  "detailedInsight.q2": "ನನ್ನ ಅತಿದೊಡ್ಡ ಹೊರಸೂಸುವಿಕೆ ಯಾವುದು?",
  "detailedInsight.q3": "ಈ ವಾರಕ್ಕೆ ಸಲಹೆಗಳು?",
  "detailedInsight.inputPlaceholder": "ಈ ವರದಿಯ ಬಗ್ಗೆ ಪ್ರಶ್ನೆ ಕೇಳಿ...",
  "leaderboard.kgCO2": "ಕೆಜಿ CO₂",
  "leaderboard.period.today": "ಇಂದು",
  "leaderboard.period.weekly": "ಸಾಪ್ತಾಹಿಕ",
  "leaderboard.period.monthly": "ಮಾಸಿಕ",
  "leaderboard.scope.global": "ಜಾಗತಿಕ",
  "leaderboard.scope.city": "ನಗರ",
  "badge.firstLog": "ಮೊದಲ ಲಾಗ್",
  "badge.sevenDay": "7-ದಿನಗಳ ಸ್ಟ್ರೀಕ್",
  "badge.carbonHero": "ಇಂಗಾಲ ಹೀರೋ",
  "badge.greenCommuter": "ಹಸಿರು ಪ್ರಯಾಣಿಕ",
  "badge.cityTop10": "ನಗರದ ಟಾಪ್ 10",
  "badge.ecoWarrior": "ಪರಿಸರ ಯೋಧ",
  "navbar.appName": "EcoLog",
  "navbar.days": "ದಿನಗಳು",
  "nav.home": "ಹೋಮ್",
  "nav.insights": "ಒಳನೋಟಗಳು",
  "nav.log": "ಲಾಗ್",
  "nav.top": "ಟಾಪ್",
  "nav.me": "ನಾನು",
  "nav.quickLog": "ತ್ವರಿತ ಲಾಗ್",
  "onboarding.welcome": "ಸುಸ್ವಾಗತ",
  "onboarding.tagline": "ನಿಮ್ಮ ಇಂಗಾಲವನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ. ನಿಮ್ಮ ಜಗತ್ತನ್ನು ಬದಲಿಸಿ.",
  "onboarding.step1.title": "ಟ್ರ್ಯಾಕ್ ಮಾಡಿ",
  "onboarding.step1.body": "ನಿಮ್ಮ ದೈನಂದಿನ ಸಾರಿಗೆ, ಆಹಾರ, ಶಕ್ತಿ ಮತ್ತು ಶಾಪಿಂಗ್ ಅನ್ನು ಸೆಕೆಂಡುಗಳಲ್ಲಿ ಲಾಗ್ ಮಾಡಿ.",
  "onboarding.step2.title": "AI ಸಲಹೆ",
  "onboarding.step2.body": "ನಿಮ್ಮ ಜೀವನಕ್ಕೆ ಅನುಗುಣವಾದ ವೈಯಕ್ತಿಕ ಸಲಹೆಗಳು — ಸಾಮಾನ್ಯ ಸಲಹೆ ಅಲ್ಲ.",
  "onboarding.step3.title": "ಪೂರ್ಣಗೊಳಿಸಿ",
  "onboarding.step3.body": "ಸ್ಟ್ರೀಕ್ ಮತ್ತು ಬ್ಯಾಡ್ಜ್ಗಳೊಂದಿಗೆ ನಿಮ್ಮ ಗುರಿಗಳನ್ನು ಮೀರಿಸಿ.",
  "onboarding.step4.title": "ಓಡಿ",
  "onboarding.step4.body": "ನಗರ ಲೀಡರ್ಬೋರ್ಡ್ ಸೇರಿ ಮತ್ತು ಸುಸ್ಥಿರತೆಯನ್ನು ಅಭ್ಯಾಸ ಮಾಡಿಕೊಳ್ಳಿ.",
  "onboarding.step5.title": "ಪ್ರಾರಂಭಿಸಿ",
  "onboarding.step5.body": "ಹಸಿರು ಭವಿಷ್ಯದತ್ತ ನಿಮ್ಮ ಪ್ರಯಾಣ ಪ್ರಾರಂಭಿಸಲು ಸೈನ್ ಇನ್ ಮಾಡಿ.",
  "onboarding.signIn": "Google ನೊಂದಿಗೆ ಸೈನ್ ಇನ್ ಮಾಡಿ",
  "category.transport": "ಸಾರಿಗೆ",
  "category.food": "ಆಹಾರ",
  "category.energy": "ಶಕ್ತಿ",
  "category.shopping": "ಶಾಪಿಂಗ್",
  "activity.car_petrol": "ಕಾರು (ಪೆಟ್ರೋಲ್)",
  "activity.car_diesel": "ಕಾರು (ಡೀಸೆಲ್)",
  "activity.bike_activa": "ಆಕ್ಟಿವಾ/ಬೈಕ್",
  "activity.e_scooter": "ಇ-ಸ್ಕೂಟರ್",
  "activity.auto_rickshaw": "ಆಟೋ ರಿಕ್ಷಾ",
  "activity.bus": "ಬಸ್",
  "activity.train": "ರೈಲು",
  "activity.flight_domestic": "ವಿಮಾನ",
  "activity.bike_ride": "ಸೈಕಲ್ ಸವಾರಿ",
  "activity.walk": "ನಡಿಗೆ",
  "activity.veg_meal": "ಸಸ್ಯಾಹಾರಿ ಊಟ",
  "activity.nonveg_meal": "ಮಾಂಸಾಹಾರಿ ಊಟ",
  "activity.dairy_meal": "ಡೈರಿ ಊಟ",
  "activity.egg_meal": "ಮೊಟ್ಟೆ ಊಟ",
  "activity.street_food": "ಸ್ಟ್ರೀಟ್ ಫುಡ್",
  "activity.swiggy_zomato": "ಸ್ವಿಗ್ಗಿ/ಜೊಮಾಟೊ",
  "activity.electricity_kwh": "ವಿದ್ಯುತ್",
  "activity.lpg_cylinder": "LPG ಸಿಲಿಂಡರ್",
  "activity.ac_hour": "AC ಬಳಕೆ",
  "activity.geyser_hour": "ಗೀಸರ್",
  "activity.washing_machine": "ವಾಷಿಂಗ್ ಮೆಷಿನ್",
  "activity.online_order": "ಆನ್ಲೈನ್ ಆರ್ಡರ್",
  "activity.clothing_item": "ಬಟ್ಟೆ ವಸ್ತು",
  "activity.electronics": "ಎಲೆಕ್ಟ್ರಾನಿಕ್ಸ್",
  "activity.plastic_bag": "ಪ್ಲಾಸ್ಟಿಕ್ ಚೀಲ",
  "activity.zeroImpact": "0 ಗ್ರಾಂ · ಶೂನ್ಯ ಪರಿಣಾಮ",
  "tab.all": "ಎಲ್ಲಾ",
  "gender.male": "ಪುರುಷ",
  "gender.female": "ಸ್ತ್ರೀ",
  "gender.other": "ಇತರೆ",
  "gender.preferNot": "ಹೇಳಲು ಇಷ್ಟವಿಲ್ಲ",
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== "undefined") {
      const saved = localStorage.getItem(LANG_KEY) as Language | null;
      if (saved && (saved === "en" || saved === "hi" || saved === "kn")) return saved;
    }
    return "en";
  });

  const [translations, setTranslations] = useState<Record<string, string> | null>(null);

  useEffect(() => {
    localStorage.setItem(LANG_KEY, language);
    document.documentElement.lang = language;

    if (language === "en") {
      setTranslations(null);
      return;
    }

    const cacheKey = `${CACHE_KEY}-v${CACHE_VERSION}-${language}`;
    const cached = localStorage.getItem(cacheKey);
    if (cached) {
      try {
        setTranslations(JSON.parse(cached));
        return;
      } catch {}
    }

    const texts = Object.values(EN);
    import("firebase/auth").then(({ getAuth }) => {
      const currentUser = getAuth().currentUser;
      if (!currentUser) return;
      return currentUser.getIdToken().then((token) => {
        return fetch(`${API_BASE}/api/translate`, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "Authorization": `Bearer ${token}`,
          },
          body: JSON.stringify({ texts, target: language }),
        })
          .then((res) => res.json())
          .then((data) => {
            if (data.translations) {
              const map: Record<string, string> = {};
              const keys = Object.keys(EN);
              keys.forEach((key, i) => {
                map[key] = data.translations[i] ?? EN[key];
              });
              setTranslations(map);
              localStorage.setItem(cacheKey, JSON.stringify(map));
            }
          })
          .catch((err) => console.error("[LanguageContext] Translation fetch failed:", err));
      });
    }).catch(() => {});
  }, [language]);

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
  }, []);

  const t = useCallback(
    (key: string): string => {
      if (language === "en") return EN[key] ?? key;
      if (translations) return translations[key] ?? EN[key] ?? key;
      const inline = language === "hi" ? HI : KN;
      return inline[key] ?? EN[key] ?? key;
    },
    [language, translations]
  );

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}
