steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg=VITE_FIREBASE_API_KEY=${_VITE_FIREBASE_API_KEY}'
      - '--build-arg=VITE_API_URL=${_VITE_API_URL}'
      - '-t'
      - 'gcr.io/my-carbon-guide/ecolog'
      - '.'
images:
  - 'gcr.io/my-carbon-guide/ecolog'
